apiVersion: v1
kind: Pod
metadata:
  name: hpcc-ansible
  labels:
    app: hpcc-ansible
spec:  # specification of the pod’s contents
  restartPolicy: Never
  containers:
    - name: hpcc-ansible
      image: "hpccsystems/ansible-ce:latest"
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /etc/HPCCSystems
          name: config-default
      stdin: true
      tty: true
      env:
        - name: NUM_ROXIE_LB
          value: "<NUM_ROXIE_LB>"
  volumes:
    - name: config-default
      persistentVolumeClaim:
        claimName: config-default
