apiVersion: v1
kind: Service
metadata: 
  name: roxie<INDEX>
  labels: 
     app: roxie<INDEX>
spec: 
  ports: 
    - name: roxie<INDEX>
      protocol: TCP
      port: 9876
      targetPort: 9876 
    - name: dfs
      protocol: TCP
      port: 7100
      targetPort: 7100
    - name: ccdmul 
      protocol: TCP
      port: 8887
      targetPort: 8887
    - name: ccdsrv 
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: ccddata 
      protocol: TCP
      port: 9001
      targetPort: 9001
    - name: ccdcli 
      protocol: TCP
      port: 9002
      targetPort: 9002
    - name: ccdsnif
      protocol: TCP
      port: 9003
      targetPort: 9003
  selector: 
     app: roxie<INDEX>
  type: LoadBalancer
